### ISSUE TITLE
Problem with removed parenthesis from calc before var

### ISSUE THREAD

**Issue by awgul** [cssnano/cssnano#645] opened 2018-10-22 19:59 UTC
Hey,

Code:
`padding-top: calc(100% / (var(--aspect-ratio)));`
gets compiled to:
`padding-top: calc(100%/var(--aspect-ratio));`

And this is wrong.
Chrome and Firefox don't respect the `var()` without parenthesis around it and so the code is not working as expected.

**Comment by andyjansson** [comment] 2018-10-22 21:08
I just tested this in both Firefox and Chrome. It works fine: https://codepen.io/anon/pen/jevrdX

**Comment by andyjansson** [comment] 2018-10-22 22:11
Wrap the property declaration in a parenthesis?

**Comment by awgul** [comment] 2018-10-23 05:12
Yes, you are right. `(16/9)` is the solution.

**Comment by shrpne** [comment] 2019-11-06 14:09
@andyjansson wrapping property declaration is a workaround.
But it doesn't mean that the issue is invalid.
Css minifier should not judge how to write css, it should be aligned to web standards and browsers implementation. 

@evilebottnawi I believe we should reopen this issue or open a new one, because it still actual.

**Comment by shrpne** [comment] 2020-08-26 16:44
@anikethsaha @evilebottnawi @TrySound @ai @andyjansson

Can it be reopened, please? I still experiencing this issue.

**Comment by evilebottnawi** [comment] 2020-08-26 16:47
What is the problem?

**Comment by shrpne** [comment] 2020-08-26 18:36
Topic starter described it well: https://github.com/cssnano/cssnano/issues/645#issue-372675004

This valid css
```css
--aspect-ratio: 16/9;
padding-top: calc(100% / (var(--aspect-ratio)));
```
becomes invalid after cssnano compilation, because cssnano removes parenthesis around of `var()`

Test case: https://jsfiddle.net/z7bsn1r8/4/

**Comment by anikethsaha** [comment] 2020-08-27 10:14
I think this should be fixed while you are declaring the variable itself.

You can use **`--aspect-ratio: (16/9);`** instead. It will work fine.

**Comment by shrpne** [comment] 2020-08-27 10:36
Imagine, if such code `padding-top: calc(100% / (var(--aspect-ratio)));` is a part of css framework. Everyone from the internet can use it and they should not be aware of what css minifier is used under the hood. Css minifier should not enforce users to avoid valid css and stick with workarounds instead.

> Though, if the style is breaking cause of the minification, it does looks like it should be fixed.

So can we reopen this issue, please?

**Comment by anikethsaha** [comment] 2020-08-27 10:39
IMO , yes

cc @evilebottnawi .

**Comment by evilebottnawi** [comment] 2020-08-27 11:26
Anyway we can't fix it here, it is bug from postcss-calc

**Comment by ludofischer** [comment] 2022-01-10 21:36
Duplicate of https://github.com/postcss/postcss-calc/issues/113, fixed in https://github.com/postcss/postcss-calc/pull/159.

**Closed by ludofischer** 2022-01-10 21:36 UTC
Labels: upstream
