### ISSUE TITLE
cssDeclarationSorter is not safe when shorthand after longhand property

### ISSUE THREAD

**Issue by ai** [cssnano/cssnano#535] opened 2018-07-04 17:48 UTC
Input:

```css
.bounce {
	animation-name: bounce;
	animation: bounce2 1s ease;
	z-index: 1442;
}
```

Output:

```css
._bounce_{animation:_bounce2_ 1s ease;animation-name:_bounce_;z-index:1442}
```

Expected output:

```css
._bounce_{animation-name:_bounce_;animation:_bounce2_ 1s ease;z-index:1442}
```

/cc @evilebottnawi 

-----
Other bug (need add tests):

Input:

```css
.class {
  border-radius: 10px;
  border-bottom-left-radius: 0;
}
```

Output:

```css
.class{border-bottom-left-radius:0;border-radius:10px}
```

-----
Other bug (need also add tests):

Input:
```css
border-width: 2px;
border-style: solid;
border-top: 0;
border-left: 0;
```

Output:
```css
border-left: 0;
border-style: solid;
border-top: 0;
border-width: 2px;
```

**Comment by evilebottnawi** [comment] 2018-07-04 17:57
Looks bug, feel free to fix, don't have time right now :disappointed:

**Comment by ai** [comment] 2018-07-04 18:03
I am not sure, that [css-declaration-sorter](https://github.com/Siilwyn/css-declaration-sorter) is safe. Seems like it was designed to use manually by the developer. And could be dangerous to run it on legacy code.

**Comment by ai** [comment] 2018-07-04 18:03
Maybe we should disable it in `default` preset and keep only in `advanced`?

**Comment by evilebottnawi** [comment] 2018-07-04 18:06
@ai in theory it is dangerous only in some cases where using idents, maybe we can handle this in safe way

**Comment by ai** [comment] 2018-07-04 18:09
@evilebottnawi it can be dangerous if the code is written wrong. Like in this example (shorthand override longhand). Yeap, we could make `css-declaration-sorter` very smart to predict it, but I am not sure, that it will be done soon.

What do you think if we will disable `css-declaration-sorter` in `default` preset and enable back when it will become smarter?

**Comment by evilebottnawi** [comment] 2018-07-04 18:14
@ai feel free to this and release patch version

**Comment by Siilwyn** [comment] 2018-07-05 12:31
:wave: chiming in, a straightforward fix would be to keep the `animation-*`, `list-style-*`, `grid-*`, `counter-*` in the same order as @evilebottnawi mentioned. Would it be an idea for me to shoot in a PR at cssnano? Think a custom order makes the most sense.

**Comment by ai** [comment] 2018-07-05 15:31
@Siilwyn yeap, but we need to keep order of any longhand/shorthand properties

**Comment by kingback** [comment] 2018-08-08 10:35
same problem when using `-webkit-background-size`

Input:

```
.a {
  background: url('xxx');
  -webkit-background-size: contain;
}
```

Output: 

```
.a{-webkit-background-size:contain;background:url(xxx)}
```

**And `-webkit-background-size` is overrided by `background`**

Expected output:

```
.a{background:url(xxx);-webkit-background-size:contain;}
```

**Comment by Siilwyn** [comment] 2018-08-08 10:41
@kingback do you include prefixed properties in your source code?

Regarding the fixed order I think I'll have time to look into it tomorrow!

**Comment by kingback** [comment] 2018-08-13 09:28
yes, some legacy code use prefixed properties to compatible with old mobile devices, maybe we can remove the vendor prefix before sort properties

**Comment by Siilwyn** [comment] 2018-08-14 11:41
Still a valid use-case, @kingback I would recommend to look at using [autoprefixer](https://github.com/postcss/autoprefixer). But I'll take a look at prefixed properties too.

**Comment by andyjansson** [comment] 2018-08-27 12:31
Given the amount of issues we have around `cssDeclarationSorter` it might be warranted to disable the plugin entirely.

**Comment by evilebottnawi** [comment] 2018-08-27 12:58
@andyjansson i think we should fix it, don't disable, can we provide list of problems here?

**Comment by andyjansson** [comment] 2018-08-27 13:06
Well the issue is that it's entirely too naïve and doesn't respect precedence. I do not believe we can easily fix it without major rewrites, which is hard given that it is an external dependency.

**Comment by evilebottnawi** [comment] 2018-08-27 13:09
@andyjansson we can move sort algorithm inside `css-declaration-sorter` in theory and don't use dependecy

**Comment by dutchenkoOleg** [comment] 2018-08-27 17:26
People, you are killing cssnano! (((

**Comment by andyjansson** [comment] 2018-08-27 18:16
@dutchenkoOleg That's an unwarranted response. What gives?

**Comment by Siilwyn** [comment] 2018-08-27 19:53
Yes I'm certain I can make this work, just need to put time and thoughts into the problem. Doesn't really matter it is external or not right? I'm willing to change parts on my end. :)

**Comment by andyjansson** [comment] 2018-08-27 21:03
@dutchenkoOleg and how are we "killing cssnano"? Like @ai says, `css-declaration-sorter` is unsafe in its current form, leading to broken CSS. We are discussing whether disabling this plugin until a resolution can be found is an appropriate course of action. 

If you have any concerns, go ahead and voice them, but we can do without the outburts and hyperboles.

**Comment by dutchenkoOleg** [comment] 2018-08-28 05:11
I think you needed to turn off this plug-in immediately, when you realized that this is unsafe, rather than discuss it "...to be or not to be..."

**Comment by kingback** [comment] 2018-08-28 05:30
agree with @andyjansson, not only this issue, there're issues like [postcss-calc/issues/48](https://github.com/postcss/postcss-calc/issues/48) makes me feel like it's unsafe to use `cssnano`, I think we should support disable plugins, like:

```
{
  preset: ['default', {
    cssDeclarationSorter: false, // disable plugin
    postcssCalc: false, // disable plugin
    discardComments: { // custom plugin config
      removeAll: true,
    }
  }]
}
```

So we can have a choice to deside which plugin we don't want to use.

**Comment by andyjansson** [comment] 2018-08-28 06:16
>I think we should support disable plugins

We've always supported that. https://cssnano.co/guides/presets#excluding-transforms

>there're issues like postcss-calc/issues/48 makes me feel like it's unsafe to use `cssnano`

The issue here is `MoOx/reduce-css-calc`. It's had a fix for the longest time, but the package has been poorly maintained.

@ai do you have access to this repo? If not, other options are to fork the code, or move the logic to `postcss-calc`.

**Comment by Siilwyn** [comment] 2018-09-13 21:14
For now keep all properties that have a shorthand in the same order in the default preset, downside being this will reduce the effectiveness of reducing size. On the advanced preset it will still sort all properties. Mostly done with this, just have to clean up the tests and add an explanation to the documentation. If it is okay with @ai @evilebottnawi? I'll finish it and create a PR in the coming days.

My plan after this is to handle the relation between longhand/shorthand properties for smarter sorting.

**Comment by ai** [comment] 2018-09-13 21:27
Yeap, send PR

**Comment by andyjansson** [comment] 2018-09-13 21:33
>For now keep all properties that have a shorthand in the same order in the default preset

@Siilwyn It's not enough to look at shorthands. There are properties which compete for the same space whilst not being a shorthand of one another. One example of this is `border-style` and `border-top`.

Respecting precedence is key here.

**Comment by Siilwyn** [comment] 2018-09-13 21:53
@andyjansson that is exactly what I mean though, `border-style` is a shorthand. So `border-top` has a shorthand property and won't be changed in order.

**Comment by andyjansson** [comment] 2018-09-13 22:15
>border-style is a shorthand. 

That depends on what you compare it with. It's a shorthand of `border-<TRBL>-style`, but it's a longhand of `border`. 

Whether it's a shorthand or not isn't really the key issue here; *precedence* is. The order of declaration makes a huge semantic difference, regardless of whether shorthand or longhand declarations are involved. 

```
border-width: 2px;
border-top-width: 0;
```


```
border-top-width: 0;
border-width: 2px;
```

The above two snippets, although being identical in what properties they contain, mean two very different things due to the order they're declared in.

**Comment by ai** [comment] 2018-09-24 19:13
Another week ended. Did we released any solution or we are still in political powerless?

It is a critical issue. We had a quick option and long option. Why we prefer to choose the worst option to do nothing?

/cc @evilebottnawi

**Comment by Siilwyn** [comment] 2018-09-24 19:22
@ai the quick option is already merged, just no version bump yet.

Meanwhile I'm waiting for feedback on my PR which is ready to be merged too.

**Comment by evilebottnawi** [comment] 2018-09-24 19:34
@ai I apologize for the current situation, but I really have a lot of work and I will not have enough time :disappointed: So I gave github/npm access to you (@ai) and @andyjansson so feel free to release, i can find time only tomorrow.

**Comment by evilebottnawi** [comment] 2018-09-24 19:43
@Siilwyn you solution is not good. Why?

It is bad to have list of properties in file https://github.com/cssnano/cssnano/pull/580/files#diff-bc4bbe1119837b527465f18f074304ff (each new option require adding to file).

A lot of changes not related to PR. Example:
From:
```css
body{font-size:100%;line-height:1.5}
```
To
```css
body{line-height:1.5;font-size:100%}
```

Why it is happens? It is not alphabetic order. We need maximum alphabetic order to better `gziping`.

Here issue about new option https://github.com/Siilwyn/css-declaration-sorter/issues/64 to fix this bug. Main idea order all property in `alphabetic` mode except `shorthard` property after `longhand` (maybe exists edge case what we should handle in other way)

**Comment by dkenul** [comment] 2018-09-24 19:54
Would it be possible to at least update the optimisations docs:
https://cssnano.co/optimisations/

to indicate that this plugin is unsafe and have it off by default? Recently updated to a newer version of cssnano in a legacy project and this threw me for a loop.

I'll make a PR for that if anyone wants. This is _not_ safe, especially when dealing with a CSS pre-processor.

**Comment by ai** [comment] 2018-09-24 19:55
I will try to release it right now

**Comment by evilebottnawi** [comment] 2018-09-24 19:57
> @dkenul 

> I'll make a PR for that if anyone wants. This is not safe, especially when dealing with a CSS pre-processor.

Please provide example.

**Comment by evilebottnawi** [comment] 2018-09-24 20:29
@dkenul don't use `cssnano`  with a CSS pre-processor. It is always unsafe. Use `cssnano` only on pure `css` code

**Comment by Siilwyn** [comment] 2018-09-24 20:35
@evilebottnawi I know that, it's not ideal but it is still much better than disabling the plugin! That is why I proposed this as the solution for now: https://github.com/cssnano/cssnano/issues/535#issuecomment-421155502

Please reconsider, I would hate it if all these hours I spend on a solution I proposed and worked on to be wasted.

**Comment by dkenul** [comment] 2018-09-24 20:36
@evilebottnawi can you elaborate? This specific issue can occur with or without a pre-processor.

**Comment by evilebottnawi** [comment] 2018-09-25 10:13
@dkenul please create new issue with example what you have in `css`, what you actually have after minification and what you expected, thanks!

**Comment by jordrake** [comment] 2018-10-12 15:29
What about the alternative where we maintain a collection of shorthand and their longhand expansions? It will still require vigilance to keep up to date but should be less change overall. Similar to https://github.com/stylelint/stylelint/blob/master/lib/reference/shorthandData.js

Perhaps also expose it as an option too to allow people to customise it such that new additions can be added outside of releases.

**Comment by evilebottnawi** [comment] 2018-10-12 15:33
@jordrake sounds good

**Comment by Siilwyn** [comment] 2018-10-12 18:57
@jordrake I already keep a collection of properties up-to-date at `css-declaration-sorter` by downloading them from the MDN docs, so that should be not much extra effort to do.

**Comment by evilebottnawi** [comment] 2020-02-20 10:55
Fixed https://github.com/cssnano/cssnano/pull/855/

**Closed by evilebottnawi** 2020-02-20 10:55 UTC
Labels: bug
