### ISSUE TITLE
[Bug] : node.getIterator is not a function

### ISSUE THREAD

**Issue by smth** [cssnano/cssnano#1172] opened 2021-07-24 08:38 UTC
**Describe the bug**
When using v5 I get `node.getIterator is not a function`. Rolling back to v4 removes the error.

**To Reproduce**
```node
const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const cssFile = path.join(__dirname, `path/to/styles.css`);

async function fetchCSS() {
  return fs.readFileSync(cssFile);
}

module.exports = async function() {
  let file = cssFile;
  let css = await fetchCSS();

  return await postcss([
      require('cssnano')  
  ])
  .process(css, { from: file })
  .then(result => {
    return {
      postCSS: result.css
    }
  });
};
```

**Expected behavior**
Return processed CSS

**Desktop**
- CSSNANO Version: 5.x 
- Plugins/presets versions: I was also using @csstools/postcss-sass 4.0

``` 
System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 8.27 GB / 15.94 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  ```

**Additional context**
Someone has reported the same issue with another postcss plugin (postcss-less) https://github.com/postcss/postcss/issues/1414

**Comment by sigveio** [comment] 2021-07-24 08:47
Thanks for your report, @smth -- before we attempt to reproduce/investigate, could you also please provide an example snippet of CSS that will trigger the error?

**Comment by sigveio** [comment] 2021-07-24 09:06
Also; have you looked at what your `css` variable contains? 

From the documentation of `readFile` and `readFileSync`:

```
If no encoding is specified (using options.encoding), the data is returned as a 
<Buffer> object. Otherwise, the data will be a string.

If options is a string, then it specifies the encoding.
```

So I'm guessing this might work better:

```js
async function fetchCSS() {
  return fs.readFileSync(cssFile, 'utf8');
}
```

**Comment by smth** [comment] 2021-07-24 09:35
I was using SCSS (via @csstools/postcss-sass). This is representative of the structure / complexity:

```scss
.my-class {
  background-color: #000;

  span {
    display: block;
  }

  &.another-class {
    img {
      max-width: 70vw;
    }
  }

  &.third-class{
    img {
      max-height: 90px;
    }
  }
}
```

**Comment by sigveio** [comment] 2021-07-24 10:23
If I generate corresponding CSS from that example and run it though cssnano it works as it should. 

From the `@csstools/postcss-sass` project page:

> Not all Sass syntax supported. Parser under development.

What lead you to believe that what you are experiencing is an issue with cssnano and not `@csstools/postcss-sass`? =)

If you can provide a minimal working example to reproduce it, that would be helpful. So a concrete example of the content of an input file and the corresponding code that will generate the error if I run it

**Comment by sigveio** [comment] 2021-07-24 10:43
From `@csstools/postcss-sass`'s parse code:

```js
try {
  this.node = gonzales.parse(this.input.css, { syntax: 'sass' })
} catch (error) {
  throw this.input.error(error.message, error.line, 1)
}
```

From what I can see they only support SASS, so the original indented syntax. 

The parser they use doesn't seem to support SCSS unless you pass in `syntax: 'scss'` as a [parameter](https://github.com/tonyganch/gonzales-pe#parameters-1).

**Comment by sigveio** [comment] 2021-07-24 10:50
Perhaps you can try this one instead: https://github.com/postcss/postcss-scss

**Comment by smth** [comment] 2021-07-24 11:40
> Perhaps their SCSS support is incomplete?

It uses dart-sass, so the most complete version. I'm not sure what the relevance is here. Surely if `postcss-sass` was the causing the error, it would do so regardless of `cssnano` version?

> What lead you to believe that what you are experiencing is an issue with cssnano and not @csstools/postcss-sass? =)

Just the reason I gave in my original post really - I've been using this setup without issue for years, and the variable that determines whether I get this error is the `cssnano` version (4.x vs 5.x). I have no idea where the problem lies, but given it's `cssnano` that has changed, this seemed like the logical place to report the issue.

> If you can provide a minimal working example to reproduce it, that would be helpful

Would an [11ty](https://github.com/11ty/eleventy/) project be minimal enough? That's what I was using when I encountered this error.

> Perhaps you can try this one instead: https://github.com/postcss/postcss-scss

That plug-in does not compile SCSS, but again, I think that's getting off topic.

**Comment by sigveio** [comment] 2021-07-24 12:12
> > Perhaps their SCSS support is incomplete?
> 
> It uses dart-sass, so the most complete version. I'm not sure what the relevance is here. Surely if `postcss-sass` was the causing the error, it would do so regardless of `cssnano` version?

If I run your example SCSS above via `cssnano` + `postcss-sass` and catch the error I get the following:

```
CssSyntaxError: <path>/input.sass:1:1: Please check validity of the block starting from line #1
    at Input.error (<path>/node_modules/postcss/lib/input.js:123:16)
    at SassParser.parse (<path>/node_modules/postcss-sass/parser.js:34:30)
    (...)
```

If you then look at the [code in `parser.js`](https://github.com/AleshaOleg/postcss-sass/blob/c4f02e2a35c33f758b563b6af38a739d8d8f610a/parser.js#L31-L35) from `postcss-sass` it runs `gonzales.parse` from `gonzales-pe` with `sass` as the syntax parameter. If I change that to `scss` and re-run my test, it works fine.

> > What lead you to believe that what you are experiencing is an issue with cssnano and not @csstools/postcss-sass? =)
> 
> Just the reason I gave in my original post really - I've been using this setup without issue for years, and the variable that determines whether I get this error is the `cssnano` version (4.x vs 5.x). I have no idea where the problem lies, but given it's `cssnano` that has changed, this seemed like the logical place to report the issue.

cssnano is built on top of PostCSS, and the change from 4.x to 5.x involved upgrading from PostCSS 7.x to 8.x. Which would for example mean that additional plugins you use also need to support PostCSS 8 AST. Like in the issue postcss/postcss#1414 that you mentioned. So cssnano is not the only variable in that upgrade I'm afraid.

> > If you can provide a minimal working example to reproduce it, that would be helpful
> 
> Would an [11ty](https://github.com/11ty/eleventy/) project be minimal enough? That's what I was using when I encountered this error.

A minimal working example to reproduce it means essentially a piece of code like what you provided in your original post here, coupled with a concrete example input that I can run through that code to get the error.

**Comment by smth** [comment] 2021-07-24 12:46
I see, so switching to cssnano 5 would be imposing a requirement on all other PostCSS plugins, that potentially isn't there when using v4?

I'll try to reproduce the error and share the exact code, when I get a chance.

**Comment by ludofischer** [comment] 2021-07-24 12:48
> I see, so switching to cssnano 5 would be imposing a requirement on all other PostCSS plugins, that potentially isn't there when using v4?

Most PostCSS plugins should work with PostCSS 8, they just output a warning in case they haven't been updated to the new API.

**Comment by sigveio** [comment] 2021-07-24 12:53
> I'll try to reproduce the error and share the exact code, when I get a chance.

Thanks =)

**Comment by smth** [comment] 2021-07-24 16:23
I just reproduced the error using the code I provided above. The CSS doesn't seem to matter, I got the same result with this stylesheet:

```scss
body {
  background-color: deeppink;
}
```

In both cases:

:heavy_check_mark: Worked as expected without cssnano
:heavy_check_mark: Worked as expected with cssnano 4.1.11
:x: Threw the error with cssnano 5.0.7

I then tried removing `postcss-sass` (and using a CSS file rather than SCSS). Similar results:

:heavy_check_mark: Worked as expected without cssnano,
:heavy_check_mark: Worked as expected with cssnano 4.1.11
:x: Threw an error with cssnano 5.0.7

Interestingly it was a different error though: 
```bash
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/to/my-project/node_modules/css-declaration-sorter/orders/alphabetical.mjs
```

**Comment by sigveio** [comment] 2021-07-24 16:37
That you are able to produce an error does unfortunately not help me understand if this is a problem with your setup or cssnano. Could you perhaps put a minimal example together in a github repo and provide me the link? Then I can run exactly what you are running, and better understand what's going on. =)

**Comment by smth** [comment] 2021-07-24 16:56
Sorry, your I thought by your earlier reply that you didn't want the repo. It's here: https://github.com/smth/cssnano-test

**Comment by sigveio** [comment] 2021-07-24 19:49
Yes, what I wanted was ideally an example without 11ty and the likes. Simple code or configuration that runs postcss with the plugin(s) without any extra layers / dependencies / stuff. 

In lack of that I was trying to patch something together with your original code and what you were saying earlier. But I see that I mistakenly ended up testing with [this](https://github.com/AleshaOleg/postcss-sass) `postcss-sass` and not `@csstools/postcss-sass`.

If I examine the result from running `@csstools/postcss-sass` alone, I notice this:

```
 lastPlugin: [Function (anonymous)] {
    postcssPlugin: 'postcss-sass',
    postcssVersion: '7.0.36'
  }
```

It seems like `@csstools/postcss-sass` installed via NPM uses PostCSS 7.0.36. 

They [added 8.x support recently](https://github.com/csstools/postcss-sass/commits/main/package.json), but haven't released it yet.

I would guess this could be the cause.

I'll leave it up to you to investigate further, as I currently do not see any indication that this is an issue with cssnano.

**Comment by ludofischer** [comment] 2021-07-24 22:33
> Interestingly it was a different error though:
> 
> ```shell
> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/to/my-project/node_modules/css-declaration-sorter/orders/alphabetical.mjs
> ```

I think you're hitting this `css-declaration-sorter` bug: https://github.com/Siilwyn/css-declaration-sorter/issues/185 Updating `css-declaration-sorter` to 6.1.1 should fix it.

**Comment by smth** [comment] 2021-07-25 08:04
> I think you're hitting this `css-declaration-sorter` bug

Sounds like it. Presumably that dependency will be updated in the next cssnano release.

**Comment by sigveio** [comment] 2021-07-25 10:42
Nice catch, @ludofischer 👍 

Well, I think you were hitting two different issues then. The one you reported initially, I believe is due to `@csstools/postcss-sass` not having released their upgrade to PostCSS 8.x.

The error comes from PostCSS internals:

```
❯ grep -rnw node_modules -e 'getIterator'
node_modules/postcss/lib/lazy-result.js:528:          visit.iterator = node.getIterator()
```

And happens because the two plugins are using two different versions of PostCSS, causing interoperability issues.

You could try pulling the latest from the `@csstools/postcss-sass` repo and use `npm link` for example to test it out.

**Comment by sigveio** [comment] 2021-07-26 11:47
I'm closing this to mark it as resolved on our end @smth - but you can still comment if you have any further questions :-)

I'd recommend you to follow up the issue over at [`@csstools/postcss-sass`](https://github.com/csstools/postcss-sass/issues)

Note that the  `css-declaration-sorter` bug was introduced in a minor version just a few days ago and quickly fixed in a patch version, so that should take care of itself if you update it with your preferred package manager ✌️

**Closed by sigveio** 2021-07-26 11:47 UTC
Labels: bug, triage
