### ISSUE TITLE
::after content breaks because quotes are being encoded

### ISSUE THREAD

**Issue by actuallymentor** [cssnano/cssnano#568] opened 2018-07-26 13:24 UTC
Hello!

Thanks so much for this wonderful package, it makes my life a lot easier :)

I'm running into an issue where:

```css
.thing:after {
  content: 'bob';
}
```

Is being nanofied to:

``` css
.thing{content:&quot;bob&quot;}
```

Am I misconfiguring cssnano of does this quality as a bug?

**Comment by evilebottnawi** [comment] 2018-07-26 13:34
@actuallymentor looks like a bug, what version `cssnano` you use?

**Comment by actuallymentor** [comment] 2018-07-26 14:35
I'm using `4.0.2`.

**Comment by actuallymentor** [comment] 2018-07-26 14:40
I just updated to `4.0.4`, the issue still persists.

**Comment by andyjansson** [comment] 2018-07-26 17:49
I can't replicate. 

**Input**

```css
.thing:after {
  content: 'bob';
}
```

**Output**

```css
.thing:after{content:"bob"}
```

**Comment by andyjansson** [comment] 2018-07-26 19:15
I'd advice you to check your lockfile. You're likely using outdated versions. I'm closing this for now.

**Closed by andyjansson** 2018-07-26 19:15 UTC
Labels: bug

**Comment by actuallymentor** [comment] 2018-07-27 08:08
All packages are at their latest stable versions.

cssnano is at:

```json
{
     "cssnano": "^4.0.4"
}
```

The relevant .lock sections:

```json
{
"cssnano": {
      "version": "4.0.4",
      "resolved": "https://registry.npmjs.org/cssnano/-/cssnano-4.0.4.tgz",
      "integrity": "sha1-ijl7XjB+Bv1+NhvxE0Sxz/h0moY=",
      "requires": {
        "cosmiconfig": "^5.0.0",
        "cssnano-preset-default": "^4.0.0",
        "is-resolvable": "^1.0.0",
        "postcss": "^6.0.0"
      }
    },
    "cssnano-preset-default": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-4.0.0.tgz",
      "integrity": "sha1-wzQoe099SfstFwqS+SFGVXiOO2s=",
      "requires": {
        "css-declaration-sorter": "^3.0.0",
        "cssnano-util-raw-cache": "^4.0.0",
        "postcss": "^6.0.0",
        "postcss-calc": "^6.0.0",
        "postcss-colormin": "^4.0.0",
        "postcss-convert-values": "^4.0.0",
        "postcss-discard-comments": "^4.0.0",
        "postcss-discard-duplicates": "^4.0.0",
        "postcss-discard-empty": "^4.0.0",
        "postcss-discard-overridden": "^4.0.0",
        "postcss-merge-longhand": "^4.0.0",
        "postcss-merge-rules": "^4.0.0",
        "postcss-minify-font-values": "^4.0.0",
        "postcss-minify-gradients": "^4.0.0",
        "postcss-minify-params": "^4.0.0",
        "postcss-minify-selectors": "^4.0.0",
        "postcss-normalize-charset": "^4.0.0",
        "postcss-normalize-display-values": "^4.0.0",
        "postcss-normalize-positions": "^4.0.0",
        "postcss-normalize-repeat-style": "^4.0.0",
        "postcss-normalize-string": "^4.0.0",
        "postcss-normalize-timing-functions": "^4.0.0",
        "postcss-normalize-unicode": "^4.0.0",
        "postcss-normalize-url": "^4.0.0",
        "postcss-normalize-whitespace": "^4.0.0",
        "postcss-ordered-values": "^4.0.0",
        "postcss-reduce-initial": "^4.0.0",
        "postcss-reduce-transforms": "^4.0.0",
        "postcss-svgo": "^4.0.0",
        "postcss-unique-selectors": "^4.0.0"
      }
    },
    "cssnano-util-get-arguments": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/cssnano-util-get-arguments/-/cssnano-util-get-arguments-4.0.0.tgz",
      "integrity": "sha1-7ToIKZ8h11dBsg87gfGU7UnMFQ8="
    },
    "cssnano-util-get-match": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/cssnano-util-get-match/-/cssnano-util-get-match-4.0.0.tgz",
      "integrity": "sha1-wOTKB/U4a7F+xeUiULT1lhNlFW0="
    },
    "cssnano-util-raw-cache": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/cssnano-util-raw-cache/-/cssnano-util-raw-cache-4.0.0.tgz",
      "integrity": "sha1-vgooVuJfGF9feivMBiTii38Xmp8=",
      "requires": {
        "postcss": "^6.0.0"
      }
    },
    "cssnano-util-same-parent": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/cssnano-util-same-parent/-/cssnano-util-same-parent-4.0.0.tgz",
      "integrity": "sha1-0qPeEDmqmLxOwlAB+gUDMMKhbaw="
    }
}
```

I've run a full `rm -rf node_modules && npm i`.

> You're likely using outdated versions.

Old versions of what? I'm happy to dig.

**Comment by andyjansson** [comment] 2018-07-27 08:19
I can't reproduce your results: https://cssnano.co/playground/

Have you checked the versions of the other dependencies? Easiest way would be to delete your [package-lock.json](https://docs.npmjs.com/files/package-lock.json) or [yarn.lock](https://yarnpkg.com/lang/en/docs/yarn-lock/) and let it regenerate upon the next install. 

Try one of the following: 

**npm**:

```
$ rm -rf node_modules/ package-lock.json
$ npm cache clean
$ npm i
```

**yarn**: 
```
$ rm -rf node_modules/ yarn.lock
$ yarn cache clean
$ yarn
```

**Comment by actuallymentor** [comment] 2018-07-27 10:11
Hmm, that did not resolve the issue.

Could you try to reproduce using node `v10.4.1`? I have a sneaking suspicion something might be wrong there.

**Comment by evilebottnawi** [comment] 2018-07-27 10:19
@actuallymentor looks you have other minification for css too, do you use webpack?

**Comment by actuallymentor** [comment] 2018-08-01 16:58
I dug deep and it turned out to be an issue with the pugjs parser.

Thank you very much for spending time on the debugging process and apologies to have misattributed the issue.

**Comment by andyjansson** [comment] 2018-08-01 17:55
>I dug deep and it turned out to be an issue with the pugjs parser.

Glad you found the cause of your issues. 

>Thank you very much for spending time on the debugging process and apologies to have misattributed the issue.

You're welcome, and it's no bother at all. If you have any more problems or questions, don't hesitate to open an issue or hit us up at gitter.
