### ISSUE TITLE
[Bug]: Postcss-SVGO warning while parsing SVG in Production build: Text data outside of node

### ISSUE THREAD

**Issue by tropicalraisel** [cssnano/cssnano#1185] opened 2021-08-27 16:28 UTC
### Describe the bug

I'm having an issue similar to #1040, and detail it here: https://github.com/TropicalRaisel/django-encore-webapp/issues/1

### Expected behaviour

No warnings

### Steps to reproduce

1. Clone my repo at https://github.com/TropicalRaisel/django-encore-webapp
2. Delete the `Encore.configureFriendlyErrorsPlugin((config) => { config.logLevel = 'ERROR' })` definition near the bottom of the `webpack.config.js` file.
3. Run `yarn build`.

### Version

5.0.8

### Preset

default

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 7.35 GB / 15.75 GB
```

### Package details

```shell
webapp@1.0.0 C:\django-encore-webapp
├─┬ @symfony/webpack-encore@1.5.0
│ ├─┬ css-loader@5.2.7
│ │ ├─┬ icss-utils@5.1.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-modules-extract-imports@3.0.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-modules-local-by-default@4.0.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-modules-scope@3.0.0
│ │ │ └── postcss@8.3.6 deduped
│ │ ├─┬ postcss-modules-values@4.0.0
│ │ │ └── postcss@8.3.6 deduped
│ │ └── postcss@8.3.6 deduped
│ ├─┬ css-minimizer-webpack-plugin@2.0.0
│ │ ├─┬ cssnano@5.0.8
│ │ │ ├─┬ cssnano-preset-default@5.1.4
│ │ │ │ ├─┬ css-declaration-sorter@6.1.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ cssnano-utils@2.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-calc@8.0.0
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-colormin@5.2.0
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-convert-values@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-discard-comments@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-discard-duplicates@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-discard-empty@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-discard-overridden@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-merge-longhand@5.0.2
│ │ │ │ │ ├── postcss@8.3.6 deduped
│ │ │ │ │ └─┬ stylehacks@5.0.1
│ │ │ │ │   └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-merge-rules@5.0.2
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-minify-font-values@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-minify-gradients@5.0.2
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-minify-params@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-minify-selectors@5.1.0
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-charset@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-display-values@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-positions@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-repeat-style@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-string@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-timing-functions@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-unicode@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-url@5.0.2
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-normalize-whitespace@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-ordered-values@5.0.2
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-reduce-initial@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-reduce-transforms@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-svgo@5.0.2
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ ├─┬ postcss-unique-selectors@5.0.1
│ │ │ │ │ └── postcss@8.3.6 deduped
│ │ │ │ └── postcss@8.3.6 deduped
│ │ │ └── postcss@8.3.6 deduped
│ │ └── postcss@8.3.6 deduped
│ └─┬ resolve-url-loader@3.1.4
│   └── postcss@7.0.36
├─┬ autoprefixer@10.3.2
│ └── postcss@8.3.6
├─┬ postcss-loader@5.0.0
│ └── postcss@8.3.6 deduped
├─┬ stylelint-config-twbs-bootstrap@2.2.3
│ └─┬ stylelint-order@4.1.0
│   ├─┬ postcss-sorting@5.0.1
│   │ └── postcss@7.0.36
│   └── postcss@7.0.36
├─┬ stylelint-webpack-plugin@3.0.1
│ └─┬ @types/stylelint@13.13.1
│   └── postcss@7.0.36
└─┬ stylelint@13.13.1
  ├─┬ @stylelint/postcss-css-in-js@0.37.2
  │ └── postcss@7.0.36 deduped
  ├─┬ @stylelint/postcss-markdown@0.36.2
  │ └── postcss@7.0.36 deduped
  ├─┬ autoprefixer@9.8.6
  │ └── postcss@7.0.36 deduped
  ├─┬ postcss-html@0.36.0
  │ └── postcss@7.0.36 deduped
  ├─┬ postcss-less@3.1.4
  │ └── postcss@7.0.36
  ├─┬ postcss-safe-parser@4.0.2
  │ └── postcss@7.0.36
  ├─┬ postcss-sass@0.4.4
  │ └── postcss@7.0.36
  ├─┬ postcss-scss@2.1.1
  │ └── postcss@7.0.36
  ├─┬ postcss-syntax@0.36.2
  │ └── postcss@7.0.36 deduped
  ├── postcss@7.0.36
  └─┬ sugarss@2.0.0
    └── postcss@7.0.36
```

**Comment by sigveio** [comment] 2021-08-29 20:37
Hey @TropicalRaisel! Thanks for your report. :-)

Would you be able to narrow it down to a more minimal reproduction please? With only cssnano and the input needed to produce the error?

**Comment by TropicalRaisel** [comment] 2021-08-29 22:51
I don't think so, since this is the only way I'm able to reproduce the error.

**Comment by sigveio** [comment] 2021-08-30 10:42
You have some dependencies that won't build on my `arm64` system, so without that it's not very actionable for me unfortunately.

But to go on a hunch from your dependency tree: what happens if you update or remove the dependencies that are using `postcss` 7? `cssnano` uses version 8 and we've had reports in the past of unexpected behaviour when these are mixed. Due to AST-differences between the major versions.

**Comment by TropicalRaisel** [comment] 2021-08-30 16:06
I just realized that `resolve-url-loader` uses PostCSS 7, and have created a PR to fix it. Manually defining the dependencies in my project changed nothing, so hopefully this fixes it.

If this is not the cause of the issue, what else can be tested?

**Comment by alexander-akait** [comment] 2021-08-30 16:08
Why you use `resolve-url-loader`?

**Comment by TropicalRaisel** [comment] 2021-08-30 16:10
@alexander-akait I don't use `resolve-url-loader` directly. [Webpack Encore uses it.](https://github.com/symfony/webpack-encore/blob/main/package.json#L45)

**Comment by alexander-akait** [comment] 2021-08-30 16:13
Maybe they need to avoid using it, current sass frameworks allow to set path to assets using variables (most of them), alternative usage - alias, also sass prepare new API for rewriting URLs, so it will be easy, `resolve-url-loader` reduce build time very well due they need source maps to rewrite `url()`, generating source maps is a very expensive operation

**Comment by TropicalRaisel** [comment] 2021-08-30 16:31
Here is Encore's documentation on `resolve-url-loader`: https://github.com/symfony/webpack-encore/blob/main/index.js#L797

Here is where `resolve-url-loader` is used: https://github.com/symfony/webpack-encore/blob/main/lib/loaders/sass.js#L32

Here is where `resolve-url-loader` is tested: https://github.com/symfony/webpack-encore/blob/main/test/loaders/sass.js

Defining the Sass loading option like so still causes the warnings:
```
  .enableSassLoader((config) => {}, {
    resolveUrlLoader: false
  })
```

**Comment by TropicalRaisel** [comment] 2021-08-31 18:43
> 
> 
> You have some dependencies that won't build on my `arm64` system, so without that it's not very actionable for me unfortunately.
> 
> But to go on a hunch from your dependency tree: what happens if you update or remove the dependencies that are using `postcss` 7? `cssnano` uses version 8 and we've had reports in the past of unexpected behaviour when these are mixed. Due to AST-differences between the major versions.

@sigveio Which dependencies are causing problems on your system?

**Comment by ludofischer** [comment] 2021-11-03 22:57
I can reproduce the warning, and it goes away if you remove the font awesome fonts in https://github.com/tropicalraisel/django-encore-webapp/blob/main/assets/styles/home.scss . I think the issue appears when a file includes a svg font like this:

```
src: url('./fonts/slick.svg#slick') format('svg');
```
The problem is that the issue does not trigger when I use cssnano and postcss-svgo alone, but only when many tools are combined like in this case or https://github.com/cssnano/cssnano/issues/1189. So I think the error comes from the interaction of  webpack, css-minimzer-webpack-plugin, resolve-url-loader, cssnano and svgo and not just cssnano and svgo.

**Comment by ludofischer** [comment] 2021-11-03 22:58
Closing as duplicate of https://github.com/cssnano/cssnano/issues/1189

**Closed by ludofischer** 2021-11-03 22:58 UTC
Labels: bug
