### ISSUE TITLE
postcss-normalize-whitespace breaks the sourcemap

### ISSUE THREAD

**Issue by andreymal** [cssnano/cssnano#629] opened 2018-10-09 13:28 UTC
Example (you can download it [here](https://home.andreymal.org/files/postcss_test2.zip)):

```
postcss_test2/
- build/
  - main.css
  - main.css.map
- src/
  - foo/
    - fooindex.css
    - vars.css
  - index.css
- package.json
- postcss.config.js
```

**Build command:** `postcss src/index.css -o build/main.css --map`

**postcss.config.js**

```javascript
module.exports = (ctx) => ({
  map: ctx.options.map,
  plugins: [
    require('postcss-import')(),
    require('postcss-normalize-whitespace')(),
  ]
})
```

**src/index.css**

```css
@import 'foo/fooindex.css';

* {
    box-sizing: border-box;
}
```

**src/foo/fooindex.css**

```css
@import './vars.css';

html, body {
    font-family: sans-serif;
}

.logo1 {
    width: calc(var(--somevar) * 2);
}

* {
    margin: 0;
    padding: 0;
}
```

**src/foo/vars.css**

```css
:root {
    --somevar: 100px * 2;
}
```

When the postcss-normalize-whitespace plugin is disabled, here is the correct sourcemap (Chromium and Firefox):

![](https://i.imgur.com/YYPCjsR.png)

But when I enable it:

![](https://i.imgur.com/5SxBRGo.png)

**Comment by evilebottnawi** [comment] 2018-10-09 13:35
@andreymal can you disable `import` plugin? Also please create minimum reproducible test repo

**Comment by andreymal** [comment] 2018-10-09 13:39
@evilebottnawi `import` plugin is required for some other plugins in my project (`postcss-custom-properties`, `postcss-mixins` etc.), so I can't disable it.

You can download the minimum reproducible test [here](https://home.andreymal.org/files/postcss_test2.zip), why do you need a repository?

**Comment by evilebottnawi** [comment] 2018-10-09 13:45
@andreymal we need disable this for determinate what problem not in `postcss-import`

**Comment by andreymal** [comment] 2018-10-09 14:12
@evilebottnawi okay, you can download another example [here](https://home.andreymal.org/files/postcss_test3.zip)

There is exactly one input file `src/main.css`, but it contains the inline sourcemap that contains info about multiple files.

**Command:** `postcss src/main.css -o build/main.css --map`

**src/main.css**: [https://pastebin.com/UTqADdEZ](https://pastebin.com/UTqADdEZ)

**postcss.config.js**

```js
module.exports = (ctx) => ({
  map: {inline: true},
  plugins: [
    require('postcss-normalize-whitespace')(),
  ]
})
```

If you will not use `postcss-normalize-whitespace` or will use any other plugin (e.g. `postcss-custom-properties`), then everything will work fine.

The sourcemap breaks only if the `postcss-normalize-whitespace` plugin is enabled

**Comment by evilebottnawi** [comment] 2018-10-09 14:15
Looks bug, feel free to investigate, i will look on this in near future

**Comment by raptor235** [comment] 2020-01-09 00:19
Just ran into the same issue... any progress on this?

**Comment by evilebottnawi** [comment] 2020-01-09 10:37
@raptor235 No, feel free to sens a PR

**Comment by ludofischer** [comment] 2021-11-04 18:04
I've tried the supplied examples with all packages updated to the latest releases (cssnano 5.0.9, postcss-cli 9.0.1, cssnano-preset-default 5.15). I can't see any difference in the source map whether or no `postcss-normalize-whitespace` is enabled. Closing this since it probably was fixed in the transition to PostCSS 8.

**Closed by ludofischer** 2021-11-04 18:04 UTC
Labels: bug
