### ISSUE TITLE
[Bug] : translate z-index:100 to z-inde: #100

### ISSUE THREAD

**Issue by camillalo** [cssnano/cssnano#1121] opened 2021-05-21 10:34 UTC
**Describe the bug**
when i use 'cssnano-preset-default' or 'cssnano-preset-advanced', this value of 'z-index' will be transformed by 'colord' as a valid color value.

**Code**
```
colour = 100
const parsed = (0, _colord.colord)(colour.toLowerCase());
```
then:
```
if (parsed.isValid()) {
if (alpha === 1) {
      const toHex = (0, _toShorthand.default)(parsed.toHex());
      const toName = parsed.toName();

      if (toName && toName.length < toHex.length) {
        return toName;
      } else {
        return toHex;   // #100
      }
    }
}
```

**Comment by ludofischer** [comment] 2021-05-21 11:17
Duplicate of https://github.com/cssnano/cssnano/issues/1113

**Closed by ludofischer** 2021-05-21 11:17 UTC
Labels: bug, triage
