### ISSUE TITLE
[Bug] : Unexpected hashes (#) were added in minified CSS

### ISSUE THREAD

**Issue by MilanAryal** [cssnano/cssnano#1119] opened 2021-05-21 04:58 UTC
**Description**
After updating cssnano to v5.0.3, an unexpected hashes (#) were added in minified CSS.

**Expected behavior**

<img width="260" alt="Screenshot 2021-05-21 103701" src="https://user-images.githubusercontent.com/9361180/119083873-83ed0300-ba20-11eb-88b9-be34c3b1a053.png">

**Unexpected result**

<img width="269" alt="Screenshot 2021-05-21 103246" src="https://user-images.githubusercontent.com/9361180/119083622-032e0700-ba20-11eb-89f3-485ac88d4d55.png">

**Desktop:**
- CSSNANO Version v5.0.3 
- WSL: Ubuntu 20.04
- Node v10.19.0
- npm v7.13.0

**Comment by ludofischer** [comment] 2021-05-21 06:29
This is a duplicate of #1115.

**Closed by ludofischer** 2021-05-21 06:29 UTC
Labels: bug, triage
