### ISSUE TITLE
[Bug] : Malformed rendering of font property

### ISSUE THREAD

**Issue by marcelkorpel** [cssnano/cssnano#995] opened 2021-02-11 21:23 UTC
**Describe the bug**
The input
```css
html {
  font: 10pt 450 "IMP Pla";
}
```
is incorrectly transformed into
```css
html{font:10pt 450,IMP Pla}
/*                ^ */
```
This leads to 'Invalid property value'.

**To Reproduce**

1. Go to [this test](https://cssnano.co/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXG5odG1sIHtcbiAgICBmb250OiAxMHB0IDQ1MCBcIklNUCBQbGFcIjtcbn1cbiIsImNvbmZpZyI6Ii8vIGNzc25hbm8gY29uZmlnXG57XG4gIFwicHJlc2V0XCIgOiBcImRlZmF1bHRcIixcbn1cbiJ9) on the playground
2. Click on 'Run'
3. See error

**Expected behavior**
The same output, but without the comma:
```css
html{font:10pt 450 IMP Pla}
/*                ^ */
```

**Comment by ludofischer** [comment] 2021-03-07 19:46
Confirmed on my end too,  5.0.0 does not fix it.

**Comment by ludofischer** [comment] 2021-06-27 14:39
Cannot reproduce it any more in 5.0.6, closing it for now although I am not sure how it was fixed.

**Closed by ludofischer** 2021-06-27 14:39 UTC
Labels: bug
