### ISSUE TITLE
discardDuplicates rule behavior

### ISSUE THREAD

**Issue by xavierfoucrier** [cssnano/cssnano#623] opened 2018-10-02 14:31 UTC
The **discardDuplicates** rule do not work if some styles differs inside each block.

For example, this:

```
.box {
  color: blue;
  font-weight: 100;
}

.box {
  font-weight: 700;
}
```

Will result with default preset in:

```
.box{color:#00f;font-weight:100;font-weight:700}
```

The expected behavior should be a remove of the **duplicate font-weight property** by taking the last one, based on the order of the cascading styles:
```
.box{color:#00f;font-weight:700}
```

Why this rule is working this way?

Thanks for your answer.
Best regards!

**Comment by andyjansson** [comment] 2018-10-02 14:38
Duplicate of  #86

**Closed by andyjansson** 2018-10-02 14:38 UTC

**Comment by xavierfoucrier** [comment] 2018-10-02 14:41
Big thanks, I didn't pay attention to this thread sorry!
Have a nice day :+1:
