### ISSUE TITLE
[Bug] : grid-name e1 -> NaN

### ISSUE THREAD

**Issue by sKopheK** [cssnano/cssnano#984] opened 2021-01-13 19:29 UTC
**Describe the bug**
Hi, rather a funny bug that can be easily workarounded, but worth to fix.

**To Reproduce**

```
div
{
    grid-area: e1;
}
```

https://cssnano.co/playground/#eyJpbnB1dCI6ImRpdlxyXG57XHJcbiAgICBncmlkLWFyZWE6IGUxO1xyXG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFwiZGVmYXVsdFwiLFxufVxuIn0=

**Expected behavior**
`grid-area: e1` is not converted to number

**Comment by illogic-al** [comment] 2021-02-12 18:00
I can confirm that this is an issue. I assume the 'e' in 'e1' is being interpreted as a exponent because not just any single character combined with a number breaks the minifier.

**Comment by ludofischer** [comment] 2021-03-19 18:53
Fixed in 5.0.0-rc.2

**Closed by ludofischer** 2021-03-19 18:53 UTC
Labels: bug

**Comment by illogic-al** [comment] 2021-03-20 16:14
Thanks @ludofischer. Just curious. What was the commit that fixed this? Or what was the underlying issue that 5.0.0 fixes?

**Comment by ludofischer** [comment] 2021-03-21 16:20
I suspect it is just the cssnano-value-parser update that fixes it, so you might want to look at that repository.

**Comment by illogic-al** [comment] 2021-03-23 03:02
Is that the repo name? I searched in GitHub and didn’t find it?

**Comment by ludofischer** [comment] 2021-03-23 09:29
Sorry, it is https://github.com/TrySound/postcss-value-parser

**Comment by illogic-al** [comment] 2021-03-25 07:51
Thanks. TIL there's [a part of the CSS3 spec that deals with identifying strings as numbers](https://www.w3.org/TR/css-syntax-3/#convert-string-to-number)
Looks like https://github.com/TrySound/postcss-value-parser/pull/58 was probably responsible for fixing this bug. 👍
