### ISSUE TITLE
[Bug]: reduceInitial ignore pointer-events not working

### ISSUE THREAD

**Issue by jamacoe** [cssnano/cssnano#1436] opened 2022-10-08 06:13 UTC
### Describe the bug

In gulp 4: disabling reduceInitial from default preset work, so obv. I'm addressing the thing correct. But { ignore : ["pointer-events"] } doesn't have any effect on the output. **pointer-events: initial** will be translated to **pointer-events: auto**.

```
...
.pipe(postcss([ cssnano({
        preset: ['default', { 
               // reduceInitial: false
               reduceInitial: { ignore : ["pointer-events"] }
        }]
}) ]))
...
```

### Expected behaviour

I expect **pointer-events: initial** to be left untouched.

### Steps to reproduce

CSS:

.test {
   pointer-events: initial;
}

### Version

5.1.13

### Preset

default

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 53.05 GB / 63.42 GB
```

### Package details

```shell
+-- autoprefixer@10.4.12
| `-- postcss@8.4.17
+-- cssnano@5.1.13
| +-- cssnano-preset-default@5.2.12
| | +-- css-declaration-sorter@6.3.1
| | | `-- postcss@8.4.17 deduped
| | +-- cssnano-utils@3.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-calc@8.2.4
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-colormin@5.3.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-convert-values@5.1.2
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-discard-comments@5.1.2
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-discard-duplicates@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-discard-empty@5.1.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-discard-overridden@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-merge-longhand@5.1.6
| | | +-- postcss@8.4.17 deduped
| | | `-- stylehacks@5.1.0
| | |   `-- postcss@8.4.17 deduped
| | +-- postcss-merge-rules@5.1.2
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-minify-font-values@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-minify-gradients@5.1.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-minify-params@5.1.3
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-minify-selectors@5.2.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-charset@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-display-values@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-positions@5.1.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-repeat-style@5.1.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-string@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-timing-functions@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-unicode@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-url@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-normalize-whitespace@5.1.1
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-ordered-values@5.1.3
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-reduce-initial@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-reduce-transforms@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-svgo@5.1.0
| | | `-- postcss@8.4.17 deduped
| | +-- postcss-unique-selectors@5.1.1
| | | `-- postcss@8.4.17 deduped
| | `-- postcss@8.4.17 deduped
| `-- postcss@8.4.17 deduped
`-- gulp-postcss@9.0.1
  +-- postcss-load-config@3.1.4
  | `-- postcss@8.4.17 deduped
  `-- postcss@8.4.17 deduped
```

**Comment by alexander-akait** [comment] 2022-10-25 13:10
@jamacoe Why you want to disable it?

**Comment by jamacoe** [comment] 2022-10-25 13:33
@alexander-akait I try to get rid of warnings reported by [CSS validator](https://jigsaw.w3.org/css-validator). It reports:
"auto is not defined by any specification as an allowed value for pointer-events, but is supported in multiple browsers"
So I set it to 'initial' but cssnano will change it to 'auto', because that's shorter.

**Comment by alexander-akait** [comment] 2022-10-25 13:41
@jamacoe Can you provide the source code of this warning? Thank you

**Comment by jamacoe** [comment] 2022-10-25 14:39
@alexander-akait 

Complete .css source to reproduce:
`.test{pointer-events:initial}`

cssnano compiles this to:
`.test{pointer-events:auto}`

Enter it interactivly at [https://jigsaw.w3.org/css-validator/#validate_by_input+with_options](https://jigsaw.w3.org/css-validator/#validate_by_input+with_options) and receive warning:
**auto is not defined by any specification as an allowed value for pointer-events, but is supported in multiple browsers**

**Comment by alexander-akait** [comment] 2022-10-25 14:45
I see, thank you

**Comment by ludofischer** [comment] 2022-10-27 19:26
The validator might be wrong, `pointer-events: auto` is defined in the specification: https://svgwg.org/svg2-draft/interact.html#PointerEventsProperty

**Comment by ludofischer** [comment] 2023-03-22 17:37
Possible duplicate of #663 (plugin options have no effect when the plugin config is nested inside a preset config)

**Comment by ludofischer** [comment] 2023-03-22 23:07
Actually the issue is specific to the way `pointer-events` is configured, it tries to read its options in the `prepare()` phase of the plugin lifecycle bu this does not work when the plugin is istantiated by cssnano.

**Closed** 2023-03-23 12:41 UTC
Labels: bug
