### ISSUE TITLE
[Bug]: postcss-normalize-whitespace less-loader css-var is error

### ISSUE THREAD

**Issue by Dio-Zhu** [cssnano/cssnano#1432] opened 2022-09-15 05:50 UTC
### Describe the bug

ERROR in ./App.css (./App.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./App.css)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

    --my-primary-color: #ee2233
}
^
Unrecognised input. Possibly missing opening '{'
      Error in /Users/mac-dio/MyCoding/workspace/tinper-next-packages/next-server/tns-app/app-provider/App.css (line 4, column 0)
Error: 

    --my-primary-color: #ee2233
}
^
Unrecognised input. Possibly missing opening '{'
      Error in /Users/mac-dio/MyCoding/workspace/tinper-next-packages/next-server/tns-app/app-provider/App.css (line 4, column 0)
    at Object.lessLoader (/Users/mac-dio/MyCoding/workspace/tinper-next-packages/next-server/tns-app/app-provider/node_modules/less-loader/dist/index.js:74:14)
 @ ./App.css
 @ ./App.jsx 13:0-19
 @ ./index.js 25:0-28 26:50-53

ERROR in ./App.css

### Expected behaviour

postcss-normalize-whitespace line 97

input : 

:root{
    --my-primary-color:#333;
}
output:
:root{--my-primary-color:#333}

want  fix output:
:root{--my-primary-color:#333;}

### Steps to reproduce

https://blog.csdn.net/jiujiuyaokan/article/details/9146941

### Version

postcss-normalize-whitespace 5.1.1

### Preset

(no preset)

### Environment

```shell
os
```

### Package details

```shell
cssnano@5.0.6
postcss@8.4.13
```

**Comment by yisibl** [comment] 2022-09-16 06:29
This looks like a problem with the less-loader? Omitting the semicolon here is a legal CSS rule.

**Comment by alexander-akait** [comment] 2022-09-16 12:38
Looks like `less-loader` generated only `--my-primary-color: #ee2233`, it is invalid CSS

**Comment by ludofischer** [comment] 2022-10-25 07:50
Closing this too as normalize-whitespace seems to have generated valid CSS and I would need the actual build configuration to reproduce (when I click on "the steps to reproduce" link, I see a blog post with the same contents as this issue).

**Closed by ludofischer** 2022-10-25 07:50 UTC
Labels: bug, triage
