### ISSUE TITLE
'TypeError: Cannot read property '0' of undefined' (postcss-merge-longhand border.js mergeRedundant)

### ISSUE THREAD

**Issue by huashengwang1989** [cssnano/cssnano#637] opened 2018-10-16 08:37 UTC
**Description**

While I'm using `optimize-css-assets-webpack-plugin`, which uses `cssnano-preset-default`, to optimise / minimize css from a Vue project in Webpack, I have encountered the following error in console:

```
TypeError: Cannot read property '0' of undefined
    at my-project-location/my-css-chunk.css:554:1
    at my-project-location/my-css-chunk.css:557:3
    at exports.default.v (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/lib/parseTrbl.js:12:14)
    at mergeRedundant (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:144:41)
    at rule.walkDecls.decl (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:462:16)
    at my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:205:16
    at my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:135:18
    at Rule.each (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:131:17)
    at Rule.walkDecls (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:203:17)
    at Object.merge (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:10)
    at _decl2.default.forEach.p (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:239:18
    at my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:135:18
    at Root.each (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/postcss/lib/container.js:237:19)
    at css (my-project-location/node_modules/cssnano-preset-default/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (my-project-location/node_modules/optimize-css-assets-webpack-plugin/node_modules/cssnano/dist/index.js:35:51)
    at <anonymous>

```
This is the part of the CSS that reports Error (This CSS is generated / extracted by respective Webpack loaders; Original is in SCSS):
```
/* ... */
.item-information-wrapper .item-info.item-stats { /* line 554 */
    font-size: 0.90em;
    padding: 6px 2px;
    border: 1px solid #e9eaec; /* line 557 */
    border-bottom: 1px solid #e9eaec !important;
    border-radius: 5px;
    background: #fff;
}
/* ... */
```

I've tried to add console outputs at `parseTrbl.js` and `decl/borders.js`:
At `parseTrbl.js`, above the `export` `return`:
```
console.log('parseTrbl: ', v, s)
```

At `rule.walkDecls` of `merge` function in `borders.js`, above the `return`:
```
console.log('walkDecls: ', config);
return mergeRedundant(config);
```
Here is the output:
```
//...
parseTrbl:  [ '#e9eaec', '#e9eaec', '#e9eaec', '#e9eaec' ] [ '#e9eaec', '#e9eaec', '#e9eaec', '#e9eaec' ]
parseTrbl:  1px [ '1px' ]
parseTrbl:  solid [ 'solid' ]
parseTrbl:  #e9eaec [ '#e9eaec' ]
walkDecls: { 
    values: [ '1px', 'solid', '#e9eaec' ],
    nextValues: [ '1px', 'solid', '#e9eaec' ],
    decl: Declaration {
        raws: { before: '', between: ':', semicolon: false },
        type: 'decl',
        source: { start: [Object], input: [Input], end: [Object] },
        prop: 'border',
        value: '1px solid #e9eaec',
        parent: Rule { /* ... */ },
    },
    nextDecl: Declaration {
         raws: { before: '', between: ':',  important: '!important',  semicolon: false },
         type: 'decl',
         source: { start: [Object], input: [Input], end: [Object] },
         prop: 'border-bottom',
         important: true,
         value: '1px solid #e9eaec',
         parent: Rule { /* ... */ },
    },
    index: 2 
}
parseTrbl: undefined undefined // <= after here it is the Error message.
```
The `mergeRedundant` seems not handling the case of `values` and `nextValues` being the same.

**Versions:**
- `optimize-css-assets-webpack-plugin`: 5.0.1
- `cssnano-preset-default`: 4.0.2
- `postcss-merge-longhand`: 4.0.6

**Comment by andyjansson** [comment] 2018-10-16 13:09
Duplicate of #618. Already fixed in master. 

@evilebottnawi can you release this?

**Closed** 2018-10-16 13:10 UTC
Labels: duplicate
