### ISSUE TITLE
[Bug] : postcss-discard-empty drops empty custom vars.

### ISSUE THREAD

**Issue by kevincox** [cssnano/cssnano#1165] opened 2021-07-14 20:34 UTC
**Describe the bug**

See for example the following code:

```css
.clear-var {
  --myvar: ;
}
```

This rule is removed which has the effect of no longer clearing the custom variable.

**Expected behavior**
Clearing custom variables should be kept.

**Desktop (please complete the following information):**
- CSSNANO Version 4.1.10
- Plugins/presets versions: postcss-discard-empty 4.0.1
- Add the output of `npx envinfo && npm ls cssnano` here

**Comment by alexander-akait** [comment] 2021-07-14 20:47
Can't reproduce https://cssnano.co/playground

**Comment by kevincox** [comment] 2021-07-14 21:03
This was using the `default` preset which the playground claims not to support (although it does compile the CSS without an error. I'll see if I can make a fully working minimal example. Maybe it is a version problem as well...

**Comment by sigveio** [comment] 2021-07-14 21:04
I believe `--myvar: initial;` plays better with var() fallback values than setting it blank; could updating your CSS be an option?

**Comment by kevincox** [comment] 2021-07-14 21:10
I managed to reproduce this by using `.clear-var{--myvar: }` so it appears that it works with a semicolon but maybe depending on the order of optimizations it can be stripped.

**Comment by alexander-akait** [comment] 2021-07-14 21:12
`;` can be sefaly removed here, and it will not break variable

**Comment by kevincox** [comment] 2021-07-14 21:14
> I believe `--myvar: initial;` plays better with var() fallback values than setting it blank

This doesn't work in my use case because I am using `--myvar` in part of a declaration, rather than the whole thing. For example `border:  1px solid var(--myvar);` to optionally set the color. I know this particular example can be written with the longhand property but that can't be done in my use case.

(My use case in general is a bit weird because I am making purposely invalid declarations after substitution, but I believe this is irrelevant to this bug.)

**Comment by kevincox** [comment] 2021-07-14 21:15
> ; can be sefaly removed here, and it will not break variable

Yes, the problem is that `.clear-var{--myvar: }` then gets stripped entirely which is an incorrect optimization.

**Comment by alexander-akait** [comment] 2021-07-14 21:18
hm, feel free to send PR

**Comment by sigveio** [comment] 2021-07-14 21:51
> > I believe `--myvar: initial;` plays better with var() fallback values than setting it blank
> 
> This doesn't work in my use case because I am using `--myvar` in part of a declaration, rather than the whole thing. For example `border: 1px solid var(--myvar);` to optionally set the color. I know this particular example can be written with the longhand property but that can't be done in my use case.
> 
> (My use case in general is a bit weird because I am making purposely invalid declarations after substitution, but I believe this is irrelevant to this bug.)

I see; and what is the desired outcome from `border: 1px solid var(--myvar);` in this case? 

If no border; then `--myvar: initial;` should still work to unset

If for example black; then using `--myvar: initial;` plus a fallback value `border: 1px solid var(--myvar, black);` 

Demo: https://jsfiddle.net/jL1u8pxb/

The `initial` value of a custom property is an empty value - and correctly interacts with both the invalidation and fallback mechanisms of val(). Just to offer you an alternative solution :-)

**Comment by alexander-akait** [comment] 2021-07-14 21:54
hm, https://jsfiddle.net/4p1ga79k/ works fine with minifed value

**Comment by sigveio** [comment] 2021-07-14 21:56
> hm, https://jsfiddle.net/4p1ga79k/ works fine with minifed value

Does it though? Shouldn't `.two` be no border ([invalidated](https://www.w3.org/TR/css-variables-1/#invalid-variables))?

**Comment by alexander-akait** [comment] 2021-07-14 21:58
Based on chrome output - not, you can add/remove spaces and result will be same

**Comment by sigveio** [comment] 2021-07-14 22:27
Ah, yeah, setting `--myvar: ;` with `border: 1px solid var(--myvar);` appears to be equal to `border: 1px solid;` -- and without color it should default to `currentColor` and in the case of this fiddle result in black indeed. I stand corrected.

While using `initial` has a "special interaction" with `val()` where it falls back to the fallback value if defined, and invalidates the declaration containing the `val()` if not.

So it would appear that the deletion by `postcss-discard-empty` is indeed unsafe

But... for a quick workaround one could still get the same behaviour then with a slight modification: 
using `--myvar: initial;` + `border: 1px solid var(--myvar, currentColor);`

**Comment by alexander-akait** [comment] 2021-07-14 22:31
> So it would appear that the deletion by postcss-discard-empty is indeed unsafe

Where? I don't see, please provide original code and transformed

**Comment by sigveio** [comment] 2021-07-14 22:43
> > So it would appear that the deletion by postcss-discard-empty is indeed unsafe
> 
> Where? I don't see, please provide original code and transformed

Oh, my bad. When you said this;

> hm, feel free to send PR

I thought you had confirmed it, and didn't check further myself. I just wanted to offer a possible work-around...

Sorry to confuse things in that regard. Actually testing it with the latest `cssnano` I'm not able to reproduce either.

```css
.clear-var {
  --myvar: ;
}
.one {
  border: 3px solid var(--myvar);
}
.two {
  border: 3px solid var(--myvar);
}
```

Becomes

```css
.clear-var{--myvar: }.one,.two{border:3px solid var(--myvar)}
```

> * CSSNANO Version 4.1.10
> * Plugins/presets versions: postcss-discard-empty 4.0.1
> * Add the output of `npx envinfo && npm ls cssnano` here

Perhaps it's related to the old version?

**Comment by alexander-akait** [comment] 2021-07-14 22:45
But, both is correct : https://jsfiddle.net/v1x8e3tg/ and https://jsfiddle.net/v1x8e3tg/1/

**Comment by sigveio** [comment] 2021-07-14 22:46
Pardon? I'm not disagreeing with you..

**Comment by sigveio** [comment] 2021-07-14 23:54
> (...) I'm not able to reproduce either.
> 
> ```css
>(...)
> ```
> 
> Becomes
> 
> ```css
> .clear-var{--myvar: }.one,.two{border:3px solid var(--myvar)}
> ```
> 
> > * CSSNANO Version 4.1.10
> > * Plugins/presets versions: postcss-discard-empty 4.0.1
> > * Add the output of `npx envinfo && npm ls cssnano` here
> 
> Perhaps it's related to the old version?

I posted the output to verify that it looks good to me 👍 

My last comment `"Perhaps [it's] related to the old version?"` was meant to say; `"Perhaps [what he reported] is related to the"` old version. Not that there was something wrong with the output I posted. 

Sorry if the phrasing was unclear.

Anyway; I tested with cssnano `4.1.10` and can confirm that it's an issue there.

Is upgrading to the latest version (`5.0.6`) an option for you @kevincox? If not; I'd use the workaround.

**Comment by kevincox** [comment] 2021-07-16 12:14
I ended up just avoiding the problem. So I mostly reported this to point out a correctness issue.

**Comment by sigveio** [comment] 2021-07-20 10:57
Thanks @kevincox - that's always appreciated. =) I'm closing this since it appears to work in the latest version

**Closed by sigveio** 2021-07-20 10:57 UTC
Labels: bug, triage
